/**
 * Additive & idempotent — creates the Compliance Management (filing calendar)
 * tables. NON-destructive; avoids `prisma db push` drops. Run then `npx prisma
 * generate`.  node scripts/addComplianceModule.js
 */
const prisma = require('../src/config/prisma');

const TABLES = [
`CREATE TABLE IF NOT EXISTS \`compliance_filings\` (
  \`id\` INT NOT NULL AUTO_INCREMENT,
  \`companyId\` INT NOT NULL,
  \`category\` VARCHAR(191) NOT NULL,
  \`title\` VARCHAR(191) NOT NULL,
  \`frequency\` VARCHAR(191) NOT NULL DEFAULT 'Monthly',
  \`periodLabel\` VARCHAR(191) NOT NULL,
  \`periodMonth\` INT NOT NULL DEFAULT 0,
  \`periodYear\` INT NOT NULL,
  \`dueDate\` VARCHAR(191) NOT NULL,
  \`status\` VARCHAR(191) NOT NULL DEFAULT 'Pending',
  \`amount\` DOUBLE NULL DEFAULT 0,
  \`filedDate\` VARCHAR(191) NULL,
  \`referenceNumber\` VARCHAR(191) NULL,
  \`challanFileData\` LONGTEXT NULL,
  \`challanFileName\` VARCHAR(191) NULL,
  \`challanMimeType\` VARCHAR(191) NULL,
  \`versionHistory\` JSON NULL,
  \`reminderDays\` INT NOT NULL DEFAULT 7,
  \`assignedTo\` VARCHAR(191) NULL,
  \`remarks\` TEXT NULL,
  \`autoGenerated\` TINYINT(1) NOT NULL DEFAULT 0,
  \`createdBy\` VARCHAR(191) NULL,
  \`createdAt\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updatedAt\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`compliance_filings_companyId_category_periodMonth_periodYear_key\` (\`companyId\`, \`category\`, \`periodMonth\`, \`periodYear\`),
  KEY \`compliance_filings_companyId_idx\` (\`companyId\`),
  KEY \`compliance_filings_companyId_status_idx\` (\`companyId\`, \`status\`),
  KEY \`compliance_filings_companyId_dueDate_idx\` (\`companyId\`, \`dueDate\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`,

`CREATE TABLE IF NOT EXISTS \`compliance_filing_audits\` (
  \`id\` INT NOT NULL AUTO_INCREMENT,
  \`companyId\` INT NOT NULL,
  \`filingId\` INT NULL,
  \`action\` VARCHAR(191) NOT NULL,
  \`performedBy\` VARCHAR(191) NULL,
  \`details\` TEXT NULL,
  \`createdAt\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (\`id\`),
  KEY \`compliance_filing_audits_companyId_idx\` (\`companyId\`),
  KEY \`compliance_filing_audits_filingId_idx\` (\`filingId\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`,
];

(async () => {
  try {
    for (const ddl of TABLES) {
      const name = /EXISTS \`([a-z_]+)\`/.exec(ddl)[1];
      await prisma.$executeRawUnsafe(ddl);
      console.log('+ ensured table', name);
    }
    console.log('Done. Run `npx prisma generate` next.');
  } catch (e) {
    console.error('Migration failed:', e.message);
    process.exitCode = 1;
  } finally {
    await prisma.$disconnect();
  }
})();
