// ─────────────────────────────────────────────────────────────────────────────
// Built-in Employee Card templates. Each is a portable design spec (front+back)
// generated by a small set of layout generators, then themed. These ship with
// the app and are available to every company; a company's own custom/edited
// templates are persisted separately (backend card_templates table).
// ─────────────────────────────────────────────────────────────────────────────
import type { CardElement, CardTemplate, CardSizeId, CardOrientation, CardTheme } from '@/types/cardDesigner';
import { cardDimensions, CARD_THEMES } from '@/types/cardDesigner';

const themeOf = (id: string): CardTheme => (CARD_THEMES.find((t) => t.id === id)?.theme) || CARD_THEMES[0].theme;

let _n = 0;
const nid = (p: string) => `${p}${(++_n).toString(36)}`;
type EOpts = Partial<Omit<CardElement, 'id' | 'type' | 'side' | 'x' | 'y' | 'w' | 'h'>>;
const E = (type: CardElement['type'], side: CardElement['side'], x: number, y: number, w: number, h: number, o: EOpts = {}): CardElement =>
  ({ id: nid(type), type, side, x: Math.round(x), y: Math.round(y), w: Math.round(w), h: Math.round(h), visible: true, ...o });

interface Dims { w: number; h: number; }

// ── Shared back side (labelled details + barcode + terms) ─────────────────────
function backCommon(d: Dims, opts: { banner?: string } = {}): CardElement[] {
  const { w, h } = d;
  const rowH = h * 0.082, rowW = w * 0.9, x = w * 0.06;
  let y = h * 0.22;
  const row = (type: CardElement['type']) => { const e = E(type, 'back', x, y, rowW, rowH, { label: true, style: { fontSize: Math.round(h * 0.032), fontWeight: 700, tint: undefined } as any }); y += rowH * 1.06; return e; };
  return [
    E('box', 'back', 0, 0, w, h * 0.14, { tint: 'primary', z: 0 }),
    E('companyName', 'back', w * 0.06, h * 0.035, w * 0.88, h * 0.07, { tint: 'bg', style: { fontSize: Math.round(h * 0.036), fontWeight: 800, align: 'center', uppercase: true } }),
    E('text', 'back', w * 0.06, h * 0.16, w * 0.88, h * 0.04, { text: opts.banner || 'Employee Information', tint: 'secondary', style: { fontSize: Math.round(h * 0.03), fontWeight: 700, align: 'center', uppercase: true, letterSpacing: 1 } }),
    row('bloodGroup'), row('emergencyContact'), row('address'), row('issueDate'), row('validUntil'),
    E('barcode', 'back', w * 0.15, h * 0.72, w * 0.7, h * 0.1),
    E('text', 'back', w * 0.06, h * 0.85, w * 0.88, h * 0.1, { text: 'This card is property of the company. If found, please return to the issuing office. Misuse is punishable.', tint: 'secondary', style: { fontSize: Math.round(h * 0.022), align: 'center', lineHeight: 1.3, opacity: 0.8 } }),
  ];
}

// ── Layout 1: classic top-banner ──────────────────────────────────────────────
function gClassic(d: Dims, o: { flat?: boolean } = {}): CardElement[] {
  const { w, h } = d;
  const hb = h * 0.23;
  const pw = w * 0.44, ph = pw * 1.05, px = (w - pw) / 2, py = h * 0.28;
  return [
    o.flat
      ? E('divider', 'front', 0, hb, w, 3, { tint: 'primary', z: 0 })
      : E('box', 'front', 0, 0, w, hb, { tint: 'primary', z: 0 }),
    E('companyLogo', 'front', w * 0.05, h * 0.045, w * 0.15, w * 0.15, { z: 1 }),
    E('companyName', 'front', w * 0.24, h * 0.05, w * 0.72, h * 0.08, { tint: o.flat ? 'primary' : 'bg', z: 1, style: { fontSize: Math.round(h * 0.038), fontWeight: 800, uppercase: true } }),
    E('tagline', 'front', w * 0.24, h * 0.135, w * 0.72, h * 0.04, { tint: o.flat ? 'secondary' : 'bg', z: 1, style: { fontSize: Math.round(h * 0.026), opacity: 0.85 } }),
    E('photo', 'front', px, py, pw, ph, { style: { radius: 10, objectFit: 'cover', borderWidth: 3, borderColor: '#ffffff' } }),
    E('name', 'front', 0, py + ph + h * 0.015, w, h * 0.06, { tint: 'text', style: { fontSize: Math.round(h * 0.045), fontWeight: 800, align: 'center' } }),
    E('designation', 'front', 0, py + ph + h * 0.075, w, h * 0.04, { tint: 'secondary', style: { fontSize: Math.round(h * 0.03), align: 'center' } }),
    E('department', 'front', 0, py + ph + h * 0.115, w, h * 0.035, { tint: 'secondary', style: { fontSize: Math.round(h * 0.026), align: 'center', opacity: 0.85 } }),
    E('employeeId', 'front', w * 0.24, py + ph + h * 0.16, w * 0.52, h * 0.05, { style: { fontSize: Math.round(h * 0.03), fontWeight: 800, align: 'center', background: '$accent', color: undefined, radius: 20 }, tint: 'primary' }),
    E('qr', 'front', (w - w * 0.26) / 2, h - w * 0.26 - h * 0.03, w * 0.26, w * 0.26),
    ...backCommon(d),
  ];
}

// ── Layout 2: left colour sidebar ─────────────────────────────────────────────
function gSidebar(d: Dims): CardElement[] {
  const { w, h } = d;
  const sb = w * 0.38;
  const pw = sb * 0.72, px = (sb - pw) / 2, py = h * 0.08;
  const cx = sb + w * 0.04, cw = w - sb - w * 0.08;
  return [
    E('box', 'front', 0, 0, sb, h, { style: { background: 'linear-gradient(160deg,$primary,$secondary)' }, z: 0 }),
    E('companyLogo', 'front', px, py, pw, pw, { z: 1, style: { objectFit: 'contain' } }),
    E('photo', 'front', px, py + pw + h * 0.03, pw, pw * 1.1, { style: { radius: 10, objectFit: 'cover', borderWidth: 3, borderColor: '#ffffff' } }),
    E('qr', 'front', px, h - pw - h * 0.05, pw, pw),
    E('companyName', 'front', cx, h * 0.08, cw, h * 0.06, { tint: 'primary', style: { fontSize: Math.round(h * 0.036), fontWeight: 800, uppercase: true } }),
    E('divider', 'front', cx, h * 0.155, cw * 0.4, 2, { tint: 'secondary' }),
    E('name', 'front', cx, h * 0.24, cw, h * 0.07, { tint: 'text', style: { fontSize: Math.round(h * 0.05), fontWeight: 800 } }),
    E('designation', 'front', cx, h * 0.32, cw, h * 0.045, { tint: 'secondary', style: { fontSize: Math.round(h * 0.032), fontWeight: 600 } }),
    E('department', 'front', cx, h * 0.40, cw, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.03), fontWeight: 700 } }),
    E('employeeId', 'front', cx, h * 0.49, cw, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.03), fontWeight: 700 } }),
    E('branch', 'front', cx, h * 0.58, cw, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.03), fontWeight: 700 } }),
    E('bloodGroup', 'front', cx, h * 0.67, cw, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.03), fontWeight: 700 } }),
    E('signature', 'front', cx, h * 0.82, cw * 0.6, h * 0.09, { style: { objectFit: 'contain' } }),
    E('text', 'front', cx, h * 0.91, cw, h * 0.04, { text: 'Authorised Signature', tint: 'secondary', style: { fontSize: Math.round(h * 0.022), opacity: 0.7 } }),
    ...backCommon(d),
  ];
}

// ── Layout 3: minimal / premium centered ──────────────────────────────────────
function gMinimal(d: Dims, o: { glass?: boolean } = {}): CardElement[] {
  const { w, h } = d;
  const pw = w * 0.4, px = (w - pw) / 2;
  return [
    E('box', 'front', w * 0.08, h * 0.06, w * 0.84, h * 0.88, { style: { background: o.glass ? 'rgba(255,255,255,0.12)' : '$bg', radius: 16, borderWidth: 1, borderColor: '$accent' }, z: 0 }),
    E('companyLogo', 'front', (w - w * 0.18) / 2, h * 0.1, w * 0.18, w * 0.18, { z: 1 }),
    E('companyName', 'front', w * 0.1, h * 0.26, w * 0.8, h * 0.05, { tint: 'primary', style: { fontSize: Math.round(h * 0.032), fontWeight: 800, align: 'center', uppercase: true, letterSpacing: 2 } }),
    E('divider', 'front', (w - w * 0.2) / 2, h * 0.32, w * 0.2, 2, { tint: 'secondary' }),
    E('photo', 'front', px, h * 0.36, pw, pw, { style: { radius: pw / 2, objectFit: 'cover', borderWidth: 3, borderColor: '$secondary' } }),
    E('name', 'front', w * 0.1, h * 0.36 + pw + h * 0.01, w * 0.8, h * 0.06, { tint: 'text', style: { fontSize: Math.round(h * 0.048), fontWeight: 800, align: 'center' } }),
    E('designation', 'front', w * 0.1, h * 0.36 + pw + h * 0.07, w * 0.8, h * 0.04, { tint: 'secondary', style: { fontSize: Math.round(h * 0.03), align: 'center', uppercase: true, letterSpacing: 1 } }),
    E('employeeId', 'front', w * 0.25, h * 0.36 + pw + h * 0.13, w * 0.5, h * 0.045, { tint: 'primary', style: { fontSize: Math.round(h * 0.028), fontWeight: 700, align: 'center' } }),
    E('qr', 'front', (w - w * 0.22) / 2, h * 0.78, w * 0.22, w * 0.22),
    ...backCommon(d),
  ];
}

// ── Layout 4: security / visitor badge ────────────────────────────────────────
function gBadge(d: Dims, o: { banner?: string; bannerTint?: 'primary' | 'secondary' } = {}): CardElement[] {
  const { w, h } = d;
  const pw = w * 0.5, px = (w - pw) / 2;
  return [
    E('box', 'front', 0, 0, w, h, { style: { background: '$bg' }, z: 0 }),
    E('box', 'front', 0, 0, w, h * 0.16, { tint: o.bannerTint || 'primary', z: 1 }),
    E('text', 'front', 0, h * 0.04, w, h * 0.08, { text: o.banner || 'IDENTITY CARD', tint: 'bg', z: 2, style: { fontSize: Math.round(h * 0.05), fontWeight: 900, align: 'center', uppercase: true, letterSpacing: 2 } }),
    E('companyLogo', 'front', w * 0.04, h * 0.19, w * 0.14, w * 0.14, { z: 2 }),
    E('companyName', 'front', w * 0.2, h * 0.20, w * 0.76, h * 0.06, { tint: 'primary', z: 2, style: { fontSize: Math.round(h * 0.032), fontWeight: 800, uppercase: true } }),
    E('photo', 'front', px, h * 0.30, pw, pw * 1.05, { style: { radius: 8, objectFit: 'cover', borderWidth: 4, borderColor: '$primary' } }),
    E('name', 'front', 0, h * 0.30 + pw * 1.05 + h * 0.01, w, h * 0.06, { tint: 'text', style: { fontSize: Math.round(h * 0.05), fontWeight: 900, align: 'center', uppercase: true } }),
    E('designation', 'front', 0, h * 0.30 + pw * 1.05 + h * 0.075, w, h * 0.04, { tint: 'secondary', style: { fontSize: Math.round(h * 0.03), align: 'center' } }),
    E('employeeId', 'front', w * 0.1, h * 0.82, w * 0.5, h * 0.07, { tint: 'bg', style: { fontSize: Math.round(h * 0.04), fontWeight: 800, align: 'center', background: '$primary', radius: 6 } }),
    E('qr', 'front', w * 0.66, h * 0.80, w * 0.26, w * 0.26),
    ...backCommon(d, { banner: o.banner }),
  ];
}

// ── Layout 5: landscape information card (the legacy Info design) ──────────────
function gInfo(d: Dims): CardElement[] {
  const { w, h } = d;
  return [
    E('box', 'front', 0, 0, w, h * 0.22, { tint: 'primary', z: 0 }),
    E('companyLogo', 'front', w * 0.03, h * 0.045, h * 0.13, h * 0.13, { z: 1 }),
    E('companyName', 'front', w * 0.14, h * 0.05, w * 0.6, h * 0.08, { tint: 'bg', z: 1, style: { fontSize: Math.round(h * 0.06), fontWeight: 800 } }),
    E('text', 'front', w * 0.14, h * 0.135, w * 0.6, h * 0.05, { text: 'Employee Information Card', tint: 'bg', z: 1, style: { fontSize: Math.round(h * 0.032), opacity: 0.85 } }),
    E('photo', 'front', w * 0.04, h * 0.3, w * 0.16, w * 0.16, { style: { radius: 8, objectFit: 'cover' } }),
    E('name', 'front', w * 0.24, h * 0.28, w * 0.5, h * 0.07, { tint: 'text', style: { fontSize: Math.round(h * 0.06), fontWeight: 800 } }),
    E('designation', 'front', w * 0.24, h * 0.37, w * 0.5, h * 0.05, { tint: 'secondary', style: { fontSize: Math.round(h * 0.036) } }),
    E('employeeId', 'front', w * 0.24, h * 0.45, w * 0.5, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.032), fontWeight: 700 } }),
    E('department', 'front', w * 0.04, h * 0.58, w * 0.44, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.032), fontWeight: 700 } }),
    E('branch', 'front', w * 0.04, h * 0.68, w * 0.44, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.032), fontWeight: 700 } }),
    E('email', 'front', w * 0.04, h * 0.78, w * 0.44, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.03), fontWeight: 700 } }),
    E('phone', 'front', w * 0.52, h * 0.58, w * 0.3, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.032), fontWeight: 700 } }),
    E('bloodGroup', 'front', w * 0.52, h * 0.68, w * 0.3, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.032), fontWeight: 700 } }),
    E('employmentType', 'front', w * 0.52, h * 0.78, w * 0.3, h * 0.05, { label: true, tint: 'text', style: { fontSize: Math.round(h * 0.03), fontWeight: 700 } }),
    E('qr', 'front', w * 0.83, h * 0.55, w * 0.14, w * 0.14),
    E('barcode', 'front', w * 0.04, h * 0.9, w * 0.5, h * 0.07),
    ...backCommon(d),
  ];
}

// ── Template factory ──────────────────────────────────────────────────────────
interface Spec { id: string; name: string; category: string; size: CardSizeId; orientation: CardOrientation; theme: string; gen: (d: Dims) => CardElement[]; frontBg?: string; backBg?: string; }
function build(spec: Spec): CardTemplate {
  const d = cardDimensions(spec.size, spec.orientation);
  _n = 0; // deterministic ids per template
  return {
    id: spec.id, name: spec.name, category: spec.category, size: spec.size, orientation: spec.orientation,
    theme: themeOf(spec.theme), frontBg: spec.frontBg, backBg: spec.backBg,
    elements: spec.gen(d),
  };
}

export const BUILTIN_TEMPLATES: CardTemplate[] = [
  // Corporate
  build({ id: 'corp-blue', name: 'Corporate Blue', category: 'Corporate', size: 'CR80', orientation: 'portrait', theme: 'blue', gen: gClassic }),
  build({ id: 'corp-dark', name: 'Corporate Dark', category: 'Corporate', size: 'CR80', orientation: 'portrait', theme: 'black', gen: gClassic, frontBg: '#0f172a', backBg: '#0f172a' }),
  build({ id: 'corp-white', name: 'Corporate White', category: 'Corporate', size: 'CR80', orientation: 'portrait', theme: 'white', gen: (d) => gClassic(d, { flat: true }) }),
  build({ id: 'executive', name: 'Executive', category: 'Corporate', size: 'CR80', orientation: 'portrait', theme: 'corporate', gen: gSidebar }),
  build({ id: 'premium-gold', name: 'Premium Gold', category: 'Corporate', size: 'CR80', orientation: 'portrait', theme: 'gold', gen: gMinimal, frontBg: 'linear-gradient(160deg,#fffef8,#f7ecc9)' }),
  // Modern
  build({ id: 'glass', name: 'Glassmorphism', category: 'Modern', size: 'CR80', orientation: 'portrait', theme: 'slate', gen: (d) => gMinimal(d, { glass: true }), frontBg: 'linear-gradient(160deg,#334155,#0ea5e9)' }),
  build({ id: 'grad-blue', name: 'Gradient Blue', category: 'Modern', size: 'CR80', orientation: 'portrait', theme: 'blue', gen: gSidebar, frontBg: 'linear-gradient(180deg,#eff6ff,#ffffff)' }),
  build({ id: 'grad-purple', name: 'Gradient Purple', category: 'Modern', size: 'CR80', orientation: 'portrait', theme: 'purple', gen: gSidebar, frontBg: 'linear-gradient(180deg,#f5f3ff,#ffffff)' }),
  build({ id: 'minimal-white', name: 'Minimal White', category: 'Modern', size: 'CR80', orientation: 'portrait', theme: 'white', gen: gMinimal }),
  build({ id: 'modern-pro', name: 'Modern Professional', category: 'Modern', size: 'CR80', orientation: 'portrait', theme: 'slate', gen: gSidebar }),
  // Industry
  build({ id: 'hospital', name: 'Hospital Staff', category: 'Industry', size: 'CR80', orientation: 'portrait', theme: 'hospital', gen: gClassic }),
  build({ id: 'school', name: 'School & College', category: 'Industry', size: 'CR80', orientation: 'portrait', theme: 'university', gen: gClassic }),
  build({ id: 'manufacturing', name: 'Manufacturing', category: 'Industry', size: 'CR80', orientation: 'portrait', theme: 'manufacturing', gen: gClassic }),
  build({ id: 'retail', name: 'Retail', category: 'Industry', size: 'CR80', orientation: 'portrait', theme: 'orange', gen: gSidebar }),
  build({ id: 'it-company', name: 'IT Company', category: 'Industry', size: 'CR80', orientation: 'portrait', theme: 'purple', gen: gSidebar, frontBg: 'linear-gradient(180deg,#faf5ff,#ffffff)' }),
  // Security
  build({ id: 'security-badge', name: 'Security Badge', category: 'Security', size: 'CR80', orientation: 'portrait', theme: 'black', gen: (d) => gBadge(d, { banner: 'SECURITY', bannerTint: 'primary' }) }),
  build({ id: 'visitor', name: 'Visitor Style', category: 'Security', size: 'visitor', orientation: 'portrait', theme: 'orange', gen: (d) => gBadge(d, { banner: 'VISITOR', bannerTint: 'primary' }) }),
  build({ id: 'rfid', name: 'RFID Style', category: 'Security', size: 'CR80', orientation: 'portrait', theme: 'slate', gen: (d) => gBadge(d, { banner: 'RFID ACCESS', bannerTint: 'primary' }) }),
  // Legacy designs preserved as templates
  build({ id: 'classic-id', name: 'Classic ID', category: 'Corporate', size: 'CR80', orientation: 'portrait', theme: 'blue', gen: gClassic }),
  build({ id: 'info-card', name: 'Information Card', category: 'Corporate', size: 'info', orientation: 'landscape', theme: 'blue', gen: gInfo }),
];

export const BUILTIN_BY_ID: Record<string, CardTemplate> = Object.fromEntries(BUILTIN_TEMPLATES.map((t) => [t.id, t]));
export const DEFAULT_TEMPLATE_ID = 'corp-blue';
export const TEMPLATE_CATEGORIES = ['Corporate', 'Modern', 'Industry', 'Security', 'Custom'];

/** Deep clone so callers can safely mutate a template (designer edits). */
export function cloneTemplate(t: CardTemplate): CardTemplate {
  return JSON.parse(JSON.stringify(t));
}
