const fs = require('fs');
const file = 'src/data/mockData.ts';
let c = fs.readFileSync(file, 'utf8');
c = c.replace(/export const defaultCompanies: Company\\[\\] = \\[[\\s\\S]*?\\];/g, 'export const defaultCompanies: Company[] = [];');
c = c.replace(/export const defaultEmployees: Employee\\[\\] = \\[[\\s\\S]*?\\];/g, 'export const defaultEmployees: Employee[] = [];');
c = c.replace(/export const defaultLeaves: LeaveRequest\\[\\] = \\[[\\s\\S]*?\\];/g, 'export const defaultLeaves: LeaveRequest[] = [];');
c = c.replace(/export const defaultPayroll: PayrollRecord\\[\\] = \\[[\\s\\S]*?\\];/g, 'export const defaultPayroll: PayrollRecord[] = [];');
c = c.replace(/export const defaultAttendance: AttendanceRecord\\[\\] = \\[[\\s\\S]*?\\];/g, 'export const defaultAttendance: AttendanceRecord[] = [];');
c = c.replace(/export const defaultDocuments: Document\\[\\] = \\[[\\s\\S]*?\\];/g, 'export const defaultDocuments: Document[] = [];');
c = c.replace(/export const defaultPayments: PaymentRecord\\[\\] = \\[[\\s\\S]*?\\];/g, 'export const defaultPayments: PaymentRecord[] = [];');
fs.writeFileSync(file, c);
console.log('Mock arrays cleared.');
