// ─────────────────────────────────────────────────────────────────────────────
// Attendance MATRIX export (ExcelJS) — builds the ONE formatted workbook used by
// BOTH the Attendance Export and the Import Template. Structure is driven by the
// shared schema (attendanceMatrix); only the ROWS differ (real vs. sample), so the
// two files are byte-for-byte structurally identical and round-trip on import.
//
// Layout:
//   ZENIAHR ATTENDANCE REPORT                         (merged title)
//   Company / Branch / Department / Attendance Type / Report Period / Month /
//   Generated On / Generated By                        (report header block)
//   [table header]  Sr No | Employee Code | Biometric ID | Employee Name |
//                   Department | Branch | <date columns…> | <summary columns…>
//   [employee rows]  P / A / HD / L / WO / H  per date  + summary totals
//   Legend: P = Present  A = Absent  …
//
// Formatting: bold header, brand-filled header row, frozen employee columns +
// header row, auto widths, alternate row colours, A4 landscape print.
// ─────────────────────────────────────────────────────────────────────────────
import { MATRIX_INFO_COLUMNS, MATRIX_SUMMARY_COLUMNS, ATT_LEGEND } from './attendanceMatrix';

export interface MatrixMeta {
  company: string;
  branch: string;
  department: string;
  attendanceType: string;   // Daily / Weekly / Monthly / Custom / Yearly
  period: string;           // "13 Jul 2026 – 19 Jul 2026"
  month: string;            // "July 2026"
  generatedOn: string;      // "15 Jul 2026 10:35 AM"
  generatedBy: string;      // "Company Head"
}

export interface MatrixEmployeeRow {
  srNo: number;
  employeeCode: string;
  biometricId: string;
  employeeName: string;
  department: string;
  branch: string;
  cells: string[];                    // one value per date header (code or count)
  summary: Record<string, any>;       // keyed by MATRIX_SUMMARY_COLUMNS[].key
}

export interface MatrixData {
  meta: MatrixMeta;
  dateHeaders: string[];              // full-date headers, e.g. "Mon 13 Jul 2026"
  rows: MatrixEmployeeRow[];
}

const NAVY = 'FF16284A';
const LIGHT = 'FFF1F5F9';
const HEADER_TXT = 'FFFFFFFF';

const thin = { style: 'thin' as const, color: { argb: 'FFD8DEE9' } };
const border = { top: thin, left: thin, bottom: thin, right: thin };

export async function downloadAttendanceMatrix(data: MatrixData, fileName: string) {
  // Lazily load ExcelJS so its ~500KB only downloads when a user actually exports,
  // keeping the Attendance page's initial bundle small.
  const ExcelJS: any = (await import('exceljs')).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = 'ZeniaHR';
  const ws = wb.addWorksheet('Attendance', {
    views: [{ state: 'frozen', xSplit: MATRIX_INFO_COLUMNS.length, ySplit: 0 }],
    pageSetup: { orientation: 'landscape', paperSize: 9, fitToPage: true, fitToWidth: 1, fitToHeight: 0, margins: { left: 0.4, right: 0.4, top: 0.5, bottom: 0.5, header: 0.3, footer: 0.3 } },
  });

  const infoCount = MATRIX_INFO_COLUMNS.length;
  const dateCount = data.dateHeaders.length;
  const totalCols = infoCount + dateCount + MATRIX_SUMMARY_COLUMNS.length;

  // ── Title ───────────────────────────────────────────────────────────────────
  ws.mergeCells(1, 1, 1, totalCols);
  const title = ws.getCell(1, 1);
  title.value = 'ZENIAHR ATTENDANCE REPORT';
  title.font = { bold: true, size: 16, color: { argb: NAVY } };
  title.alignment = { horizontal: 'center', vertical: 'middle' };
  ws.getRow(1).height = 26;

  // ── Report header block ───────────────────────────────────────────────────────
  const metaLines: [string, string][] = [
    ['Company', data.meta.company],
    ['Branch', data.meta.branch],
    ['Department', data.meta.department],
    ['Attendance Type', data.meta.attendanceType],
    ['Report Period', data.meta.period],
    ['Month', data.meta.month],
    ['Generated On', data.meta.generatedOn],
    ['Generated By', data.meta.generatedBy],
  ];
  let r = 3;
  for (const [label, value] of metaLines) {
    const lc = ws.getCell(r, 1);
    lc.value = label;
    lc.font = { bold: true, color: { argb: NAVY } };
    ws.mergeCells(r, 2, r, Math.min(6, totalCols));
    const vc = ws.getCell(r, 2);
    vc.value = `: ${value || '—'}`;
    vc.alignment = { horizontal: 'left' };
    r++;
  }

  // ── Table header row ──────────────────────────────────────────────────────────
  const headerRowIdx = r + 1;
  const headers = [
    ...MATRIX_INFO_COLUMNS.map((c) => c.header),
    ...data.dateHeaders,
    ...MATRIX_SUMMARY_COLUMNS.map((c) => c.header),
  ];
  const hRow = ws.getRow(headerRowIdx);
  headers.forEach((h, i) => {
    const cell = hRow.getCell(i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: HEADER_TXT }, size: 10 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
    cell.border = border;
  });
  hRow.height = 30;

  // ── Employee rows ─────────────────────────────────────────────────────────────
  data.rows.forEach((row, ri) => {
    const values = [
      row.srNo, row.employeeCode, row.biometricId, row.employeeName, row.department, row.branch,
      ...row.cells,
      ...MATRIX_SUMMARY_COLUMNS.map((c) => row.summary[c.key] ?? 0),
    ];
    const xlRow = ws.getRow(headerRowIdx + 1 + ri);
    values.forEach((v, i) => {
      const cell = xlRow.getCell(i + 1);
      cell.value = v as any;
      cell.border = border;
      cell.font = { size: 10 };
      // Info columns left-aligned; date + summary centred.
      cell.alignment = { horizontal: i < infoCount ? 'left' : 'center', vertical: 'middle' };
      if (ri % 2 === 1) cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LIGHT } };
    });
  });

  // ── Legend footer ─────────────────────────────────────────────────────────────
  const legendRowIdx = headerRowIdx + 1 + data.rows.length + 1;
  ws.mergeCells(legendRowIdx, 1, legendRowIdx, totalCols);
  const lg = ws.getCell(legendRowIdx, 1);
  lg.value = ATT_LEGEND;
  lg.font = { italic: true, size: 9, color: { argb: 'FF64748B' } };
  lg.alignment = { horizontal: 'left' };

  // ── Widths + freeze the header row ────────────────────────────────────────────
  const widths = [
    ...MATRIX_INFO_COLUMNS.map((c) => c.width),
    ...data.dateHeaders.map((h) => Math.max(7, Math.min(16, h.length + 1))),
    ...MATRIX_SUMMARY_COLUMNS.map((c) => Math.max(8, c.header.length + 1)),
  ];
  widths.forEach((w, i) => { ws.getColumn(i + 1).width = w; });
  // Freeze employee columns (xSplit) AND everything down to the table header (ySplit).
  ws.views = [{ state: 'frozen', xSplit: infoCount, ySplit: headerRowIdx }];

  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = fileName;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(a.href);
}
