// ─────────────────────────────────────────────────────────────────────────────
// cardRenderer — server-side HTML twin of the frontend <GreetingCard/> component
// (frontend/src/pages/CommunicationCenter.tsx). It produces a self-contained HTML
// document whose single .card element renders the EXACT same design the user sees
// in the HRMate Template Gallery preview: the portable layout JSON spec (gradient
// + accent + artwork + one of 5 structural layouts + display font + emoji
// decorations), so the PNG generated by puppeteer is identical to the preview.
//
// Differences from the React preview are intentional and only make a real send
// richer than the sample preview:
//   • placeholders are filled with the REAL employee/company context (not sample)
//   • the photo frame shows the employee's actual photo when available (the
//     preview always shows sample initials because it has no real employee)
//
// This module renders only — it never talks to Meta, the DB, or the queue.
// ─────────────────────────────────────────────────────────────────────────────

const placeholders = require('./whatsappPlaceholders');

// Fixed card geometry. WhatsApp displays a 4:5 portrait nicely; 1080×1350 keeps
// it crisp. container-type:inline-size makes every `cqw` resolve against 1080px
// exactly as the browser preview does against its own width.
const CARD_W = 1080;
const CARD_H = 1350;

// ── helpers ──────────────────────────────────────────────────────────────────
const esc = (s) => String(s == null ? '' : s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const parseLayout = (raw) => {
  if (!raw) return null;
  if (typeof raw === 'object') return raw;
  try { return JSON.parse(raw); } catch { return null; }
};

// ── decoration sets — mirrors ART in CommunicationCenter.tsx ──────────────────
const ART = {
  birthday: { items: ['🎈', '🎂', '🎉', '🎊', '🎁', '🎈', '🧁'], flair: 'confetti' },
  anniversary: { items: ['🏆', '⭐', '🎗️', '✨', '🥂'], flair: 'sparkle' },
  welcome: { items: ['👋', '🎉', '✨', '🎊', '🌟'], flair: 'confetti' },
  farewell: { items: ['💐', '🌸', '💗', '🌷', '✨'], flair: 'sparkle' },
  promotion: { items: ['🚀', '⭐', '📈', '✨', '🎯'], flair: 'sparkle' },
  award: { items: ['🏆', '🥇', '⭐', '🎖️', '✨'], flair: 'sparkle' },
  finance: { items: ['💰', '🪙', '💸', '✨', '📊'] },
  document: { items: ['🧾', '✅', '📄', '✨'] },
  notice: { items: ['📢', '📌', '📋', '✨'] },
  celebration: { items: ['🎊', '🎉', '✨', '🥳', '🎈'], flair: 'confetti' },
  diwali: { items: ['🪔', '✨', '🎆', '🪔', '🌟', '🪔'], flair: 'sparkle', glow: '#f59e0b' },
  holi: { items: ['🎨', '💦', '🌈', '🟣', '🟡', '🔵', '🟢'], flair: 'colors' },
  eid: { items: ['🌙', '🕌', '🏮', '✨', '⭐'], flair: 'sparkle' },
  christmas: { items: ['🎄', '❄️', '🎅', '🎁', '⛄', '🔔'], flair: 'snow' },
  newyear: { items: ['🎆', '🥂', '🎉', '✨', '🍾', '🎊'], flair: 'confetti' },
  tricolor: { items: ['🇮🇳', '🎗️', '🕊️', '✨'], flair: 'tricolor' },
  navratri: { items: ['🪕', '💃', '🌸', '✨', '🔱'], flair: 'sparkle' },
  rakhi: { items: ['🪢', '🌸', '💐', '✨', '💝'] },
  janmashtami: { items: ['🦚', '🪈', '🧈', '✨', '🌸'] },
  ganesh: { items: ['🐘', '🌺', '🪔', '✨', '🌼'] },
  kite: { items: ['🪁', '☀️', '🪁', '✨', '🌬️'] },
  shivratri: { items: ['🔱', '🕉️', '🐍', '✨', '🌙'] },
  womensday: { items: ['💜', '🌸', '🌷', '✨', '💐'], flair: 'sparkle' },
  labour: { items: ['🛠️', '⚙️', '👷', '✨', '🏗️'] },
  flowers: { items: ['🌷', '🌸', '💐', '🌼', '🌺'], flair: 'sparkle' },
  formal: { items: ['👔', '🎩', '⭐', '✨'] },
};
const SCATTER = [[5, 7], [9, 80], [27, 4], [34, 88], [58, 5], [66, 85], [85, 16], [88, 70], [48, 92]];

// ── context / design resolution ──────────────────────────────────────────────
// Real token map (extends the shared WhatsApp placeholder context with the two
// extra tokens the image spec lists: employee_id + branch_name).
const buildCtx = (employee = {}, company = {}, branch) => {
  const ctx = placeholders.buildContext(employee, company);
  ctx.employee_id = employee.employeeId || employee.empId || employee.code || '';
  ctx.branch_name = (branch && (branch.name || branch.branchName)) || employee.branchName || '';
  return ctx;
};

// Fill {{tokens}} with REAL values. Image tokens (employee_photo / company_logo)
// are stripped from text just like the frontend does — they are rendered as
// actual images, never inline text.
const fillWith = (text, ctx) => String(text || '')
  .replace(/\{\{\s*(\w+)\s*\}\}/g, (m, k) => {
    if (k === 'employee_photo' || k === 'company_logo') return '';
    return Object.prototype.hasOwnProperty.call(ctx, k) ? (ctx[k] || '') : m;
  })
  .replace(/\s{2,}/g, ' ').trim();

// Mirror of designOf() — merge top-level template fields + parsed layout JSON.
const designOf = (item, ctx, brandName, brandLogo) => {
  const layout = parseLayout(item && item.layout) || {};
  const theme = (item && item.theme && item.theme.background) ? item.theme : (layout.theme || {});
  const bg = theme.background
    || (theme.bg1 ? `linear-gradient(135deg,${theme.bg1},${theme.bg2 || theme.bg1})` : 'linear-gradient(135deg,#eef2ff,#e2e8f0)');
  const showPhotoRaw = (item && (item.showEmployeePhoto != null ? item.showEmployeePhoto : item.employeePhotoPlaceholder));
  return {
    bg, accent: theme.accent || '#4f46e5', text: theme.text || '#1e293b',
    font: theme.font || "'Trebuchet MS',sans-serif",
    emoji: theme.emoji || layout.emoji || (item && item.emoji) || '🎉',
    art: theme.art || layout.art || (item && item.art) || 'celebration',
    layoutKind: theme.layoutKind || layout.layoutKind || (item && item.layoutKind) || 'classic',
    greeting: fillWith((item && (item.greetingTitle || item.subject || item.title)) || layout.greetingTitle || 'Greetings', ctx),
    subtitle: fillWith((item && item.subtitle) != null ? item.subtitle : (layout.subtitle || ''), ctx),
    body: fillWith((item && item.body) || layout.body || '', ctx),
    signoff: fillWith((item && item.signoff) || layout.signoff || brandName || '', ctx),
    showPhoto: showPhotoRaw !== false && (showPhotoRaw != null ? showPhotoRaw : (layout.showPhoto !== false)),
    bgImage: (item && item.backgroundImage) || '',
    logo: (item && item.companyLogo) || brandLogo || '',
  };
};

// ── markup fragments ─────────────────────────────────────────────────────────
const cardArt = (art, accent) => {
  const spec = ART[art] || ART.celebration;
  let html = '';
  if (spec.flair === 'tricolor') {
    html += `<div style="position:absolute;left:0;top:0;width:100%;height:4cqw;background:#FF9933"></div>`;
    html += `<div style="position:absolute;bottom:0;left:0;width:100%;height:4cqw;background:#138808"></div>`;
  }
  if (spec.flair === 'confetti') {
    const cols = [accent, '#f472b6', '#34d399', '#60a5fa', '#fbbf24'];
    SCATTER.slice(0, 7).forEach((p, i) => {
      html += `<span style="position:absolute;border-radius:2px;top:${(p[0] + 3) % 95}%;left:${(p[1] + 5) % 95}%;width:2.4cqw;height:2.4cqw;background:${cols[i % 5]};transform:rotate(${i * 40}deg);opacity:.85"></span>`;
    });
  }
  if (spec.flair === 'snow') {
    for (let i = 0; i < 10; i++) {
      html += `<span style="position:absolute;border-radius:9999px;background:#fff;top:${(i * 9 + 4) % 92}%;left:${(i * 17 + 6) % 92}%;width:1.8cqw;height:1.8cqw;opacity:.8"></span>`;
    }
  }
  if (spec.flair === 'colors') {
    const cols = ['#a855f7', '#ec4899', '#f59e0b', '#10b981', '#3b82f6', '#ef4444'];
    SCATTER.slice(0, 6).forEach((p, i) => {
      html += `<span style="position:absolute;border-radius:9999px;top:${p[0]}%;left:${p[1]}%;width:6cqw;height:6cqw;background:${cols[i % 6]};filter:blur(1px);opacity:.5"></span>`;
    });
  }
  spec.items.forEach((em, i) => {
    const p = SCATTER[i % SCATTER.length];
    const glow = spec.glow ? `drop-shadow(0 0 4px ${spec.glow})` : 'none';
    html += `<span style="position:absolute;top:${p[0]}%;left:${p[1]}%;font-size:7cqw;transform:rotate(${(i % 2 ? 1 : -1) * (8 + i * 4)}deg);opacity:.92;filter:${glow}">${em}</span>`;
  });
  return `<div style="position:absolute;inset:0;overflow:hidden;pointer-events:none">${html}</div>`;
};

// Photo frame — real employee photo when present, else initials disc (preview).
const photoFrame = (accent, size, name, photo) => {
  const ring = `width:${size}cqw;height:${size}cqw;border:${size * 0.07}cqw solid #fff;box-shadow:0 0 0 ${size * 0.05}cqw ${accent};border-radius:9999px;overflow:hidden`;
  if (photo) {
    return `<div style="${ring};background:#e2e8f0"><img src="${esc(photo)}" style="width:100%;height:100%;object-fit:cover" /></div>`;
  }
  const initials = String(name || 'OM PATEL').split(' ').slice(0, 2).map((w) => w[0] || '').join('');
  return `<div style="${ring};display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#cbd5e1,#94a3b8)">`
    + `<span style="font-weight:800;color:#fff;font-size:${size * 0.34}cqw">${esc(initials)}</span></div>`;
};

const logoChip = (logo, brand, light) => {
  if (logo) return `<img src="${esc(logo)}" alt="logo" style="height:7cqw;max-width:40%;object-fit:contain" />`;
  const bg = light ? 'rgba(255,255,255,0.22)' : 'rgba(15,23,42,0.08)';
  const col = light ? '#fff' : '#334155';
  return `<span style="display:inline-flex;align-items:center;border-radius:4px;font-weight:700;font-size:3.2cqw;padding:1cqw 2cqw;background:${bg};color:${col}">${esc(brand)}</span>`;
};

// Text atoms (mirror Title/Name/Sub/Body/Sign).
const titleEl = (d, color, size) => `<p style="font-weight:800;line-height:1.25;filter:drop-shadow(0 1px 1px rgba(0,0,0,.05));color:${color};font-size:${size}cqw">${d.emoji} ${esc(d.greeting)}</p>`;
const nameEl = (name, color) => `<p style="font-weight:800;line-height:1;color:${color};font-size:7cqw">${esc(name)}</p>`;
const subEl = (d, color) => d.subtitle ? `<p style="font-weight:600;color:${color};font-size:3.6cqw;opacity:.85">${esc(d.subtitle)}</p>` : '';
const bodyEl = (d, color) => d.body ? `<p style="line-height:1.375;color:${color};font-size:3.7cqw;opacity:.92">${esc(d.body)}</p>` : '';
const signEl = (d, color) => d.signoff ? `<p style="font-weight:600;font-style:italic;color:${color};font-size:3.4cqw;opacity:.9">${esc(d.signoff)}</p>` : '';

// ── the five structural layouts (mirror GreetingCard) ────────────────────────
const layoutHtml = (d, name, photo, brand) => {
  const dark = '#1f2937';
  const baseBg = d.bgImage
    ? `background-image:url(${esc(d.bgImage)});background-size:cover;background-position:center`
    : `background:${d.bg}`;
  const art = cardArt(d.art, d.accent);
  const showPhoto = d.showPhoto;

  if (d.layoutKind === 'banner') {
    return `
      <div style="position:absolute;left:0;top:0;width:100%;height:46%;${baseBg}">
        ${art}
        <div style="position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:0 6cqw;text-align:center">
          <div style="position:absolute;left:4cqw;top:4cqw">${logoChip(d.logo, brand, true)}</div>
          ${titleEl(d, d.text, 8.5)}
        </div>
      </div>
      <div style="position:absolute;bottom:0;left:0;display:flex;width:100%;flex-direction:column;align-items:center;padding:0 7cqw 6cqw;text-align:center;height:58%;justify-content:flex-end;gap:1.6cqw">
        ${showPhoto ? `<div style="position:absolute;left:50%;transform:translateX(-50%);top:-9cqw">${photoFrame(d.accent, 26, name, photo)}</div>` : ''}
        <div style="height:${showPhoto ? '15cqw' : '0'}"></div>
        ${nameEl(name, dark)}${subEl(d, dark)}${bodyEl(d, dark)}${signEl(d, d.accent)}
      </div>`;
  }
  if (d.layoutKind === 'frame') {
    return `
      <div style="position:absolute;inset:0;${baseBg}">${art}</div>
      <div style="position:absolute;inset:6cqw;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;border:0.8cqw double ${d.accent};border-radius:3cqw;padding:5cqw;gap:2cqw;background:rgba(0,0,0,0.12)">
        ${logoChip(d.logo, brand, true)}
        ${titleEl(d, d.text, 8)}
        ${showPhoto ? photoFrame(d.accent, 26, name, photo) : ''}
        ${nameEl(name, d.text)}${subEl(d, d.text)}${bodyEl(d, d.text)}${signEl(d, d.accent)}
      </div>`;
  }
  if (d.layoutKind === 'sidebar') {
    return `
      <div style="position:absolute;inset:0;display:flex">
        <div style="position:relative;display:flex;flex-direction:column;align-items:center;justify-content:center;width:42%;${baseBg}">
          ${art}
          <div style="position:relative;z-index:10;text-align:center;font-size:20cqw">${d.emoji}</div>
          <div style="position:absolute;bottom:4cqw">${logoChip(d.logo, brand, true)}</div>
        </div>
        <div style="display:flex;flex:1;flex-direction:column;justify-content:center;background:#fff;padding:0 5cqw;text-align:left;gap:1.8cqw">
          ${titleEl(d, d.accent, 7.5)}
          ${showPhoto ? photoFrame(d.accent, 22, name, photo) : ''}
          ${nameEl(name, dark)}${subEl(d, dark)}${bodyEl(d, dark)}${signEl(d, d.accent)}
        </div>
      </div>`;
  }
  if (d.layoutKind === 'split') {
    return `
      <div style="position:absolute;inset:0;background:#fff"></div>
      <div style="position:absolute;left:0;top:0;width:100%;height:60%;${baseBg};clip-path:polygon(0 0,100% 0,100% 78%,0 100%)">
        ${art}
        <div style="position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;padding:7cqw 6cqw 0;text-align:center">
          <div style="position:absolute;left:4cqw;top:4cqw">${logoChip(d.logo, brand, true)}</div>
          ${titleEl(d, d.text, 8.5)}
        </div>
      </div>
      <div style="position:absolute;bottom:0;left:0;display:flex;width:100%;flex-direction:column;align-items:center;padding:0 7cqw 6cqw;text-align:center;height:52%;justify-content:flex-end;gap:1.6cqw">
        ${showPhoto ? `<div style="position:absolute;left:50%;transform:translateX(-50%);top:-8cqw">${photoFrame(d.accent, 24, name, photo)}</div>` : ''}
        <div style="height:${showPhoto ? '13cqw' : '0'}"></div>
        ${nameEl(name, dark)}${subEl(d, dark)}${bodyEl(d, dark)}${signEl(d, d.accent)}
      </div>`;
  }
  // classic (default)
  return `
    <div style="position:absolute;inset:0;${baseBg}">${art}</div>
    <div style="position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:0 7cqw;text-align:center;gap:2cqw">
      ${logoChip(d.logo, brand, false)}
      <div style="font-size:13cqw;line-height:1">${d.emoji}</div>
      ${titleEl(d, d.accent, 7.5)}
      ${showPhoto ? photoFrame(d.accent, 24, name, photo) : ''}
      ${nameEl(name, d.text)}${subEl(d, d.text)}
      <div style="width:24cqw;height:0.5cqw;background:${d.accent};opacity:.6"></div>
      ${bodyEl(d, d.text)}${signEl(d, d.accent)}
    </div>`;
};

// ── public API ───────────────────────────────────────────────────────────────
// Build the full HTML document for one personalized greeting card.
//   template — the communication_templates row (carries layout JSON + fields)
//   employee — the recipient (name/photo/designation/department/employeeId/dates)
//   company  — branding source (name/logo)
//   branch   — optional branch (for {{branch_name}})
const buildCardHtml = ({ template, employee = {}, company = {}, branch } = {}) => {
  const ctx = buildCtx(employee, company, branch);
  const brandName = ctx.company_name || 'Company';
  const brandLogo = ctx.company_logo || '';
  const d = designOf(template, ctx, brandName, brandLogo);
  const empName = ctx.employee_name || 'Employee';
  const empPhoto = ctx.employee_photo || '';
  const inner = layoutHtml(d, empName, empPhoto, brandName);
  return `<!doctype html><html><head><meta charset="utf-8" />
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  html,body{background:#fff}
  .card{position:relative;width:${CARD_W}px;height:${CARD_H}px;container-type:inline-size;overflow:hidden;font-family:${d.font}}
  .card p{margin:0}
</style></head>
<body><div class="card">${inner}</div></body></html>`;
};

module.exports = { buildCardHtml, CARD_W, CARD_H, designOf, buildCtx, ART };
